### ISSUE TITLE
Add compilation tooling

### ISSUE THREAD

**Issue by briandennis** [dawnlabs/photosorcery#5]
The new .webp support requires `cgo` which complicates cross compilation. This should be accounted for by:

- [x]  adding documentation specifying build dependencies (Docker and [xgo](https://github.com/karalabe/xgo))

- [x] adding a Makefile that handles dependencies and compilation

**Comment by ericadamski** [comment]
@briandennis is a makefile necessary? It says here the default build is for all architectures https://github.com/karalabe/xgo#limit-build-targets

**Comment by briandennis** [comment]
Sorry, that was poorly worded on my part! I was envisioning the makefile would handle more than just executing the `xgo` command. Ideally, it would tackle multiple tasks (install package dependencies, fetch xgo container, fetch xgo cli, and build for desired platforms) so that if Docker and Go are installed, all that needs to be done after a fresh clone is run `make`.

I don't know if we need to compile for all platforms and architectures by default. Limiting it to darwin, windows, and linux for amd64 should be sufficient for most use cases.

**Comment by ericadamski** [comment]
I see great idea!

**Comment by ericadamski** [comment]
@briandennis I am walking through the install instructions for the first part of this issue but when I run `make` I cannot seem to get `xgo` to run.

```
make: xgo: No such file or directory
```

Maybe it is my go environment, I am new to GoLang is there something I am missing?

**Comment by ericadamski** [comment]
This is what the issue was 😞 https://github.com/karalabe/xgo/issues/97#issuecomment-363684189
